sudo: false
cache: bundler

before_install:
  - gem update bundler

rvm:
  - "2.4.5"
  - "2.5.3"
  - "2.6.1"
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.beta.gemfile

matrix:
  exclude:
    - rvm: 2.4.5
      gemfile: gemfiles/rails_6.0.beta.gemfile

script: "bundle exec rake spec"
